name: eth_sig_util
description: Ethereum signature utility porting from JS
version: 0.0.9
publish_to: none
homepage: https://wakumo.vn
repository: https://github.com/wakumo/eth-sig-util

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  pointycastle: ^3.0.1
  equatable: ^2.0.3
  collection: ^1.14.11
  buffer: ^1.0.6
  convert: ^3.0.0

dev_dependencies:
  test: ^1.17.10
